export const ActionsTypes = {
  GET_PRODUCT: "GET_PRODUCT",
  GET_PRODUCT_BY_ID: "GET_PRODUCT_BY_ID",
  ERROR_PRODUCT: "ERROR_PRODUCT",
  FILTER_PRODUCT_BY_GENDER: "FILTER_PRODUCT_BY_GENDER",
  FILTER_PRODUCT_BY_PRICE: "FILTER_PRODUCT_BY_PRICE",
  FILTER_PRODUCT_BY_RATING: "FILTER_PRODUCT_BY_RATING",
  FILTER_PRODUCT_BY_NAME: "FILTER_PRODUCT_BY_NAME",
  SELECT_PRODUCT_BY_ID: "SELECT_PRODUCT_BY_ID",

  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  DELETE_PRODUCT_FROM_CART: "DELETE_PRODUCT_FROM_CART",
  ADD_ITEM: "ADD_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
  GET_TOTAL_PRICE: "GET_TOTAL_PRICE",
  CLEAR_CART: "CLEAR_CART",
};
